Repository prgrms-web-devcourse/Team-Books-CheckMoi-FE, pull requests merged in 2022-08, with the labels that each got.

#18 #9/feat/layout topbar
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  features/Topbar/UserProfile/index.ts
  features/Topbar/UserProfile/style.tsx
  features/Topbar/index.ts
  features/Topbar/style.tsx
  next.config.js
  package.json
  pages/_app.tsx
  pages/layoutTest/index.tsx
  pages/style.tsx
  yarn.lock
Labels: 리뷰 요청

#19 #17/feat/study cotent
  components/StudyContent/StudyContent.stories.tsx
  components/StudyContent/StudyContent.tsx
  components/StudyContent/index.ts
  components/StudyContent/style.tsx
Labels: 리뷰 요청, 프론트

#16 #13/feat/study detail card
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  components/StudyDetailCard/StudyState/StudyState.stories.tsx
  components/StudyDetailCard/StudyState/StudyState.tsx
  components/StudyDetailCard/StudyState/index.ts
  components/StudyDetailCard/StudyState/style.tsx
  components/StudyDetailCard/helper.ts
  components/StudyDetailCard/index.ts
  components/StudyDetailCard/style.tsx
  types/userType.ts
Labels: 리뷰 요청

#21 #14/api naver api
  apis/api.ts
  apis/book.ts
  apis/index.ts
  apis/naver.ts
  next.config.js
  package.json
  pages/index.tsx
  types/bookType.ts
  yarn.lock
Labels: 리뷰 요청, 프론트, API data, Type: 기능추가

#29 #26/feat/main page
  components/BookCard/style.tsx
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  styles/MainPageStyle.tsx
  styles/PageStyle.tsx
  types/testType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가

#31 #25/feat/login modal
  features/Topbar/LoginButton/LoginButton.tsx
  features/Topbar/LoginButton/index.ts
  features/Topbar/LoginButton/style.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  features/Topbar/style.tsx
  pages/login/index.tsx
  public/images/kakao_login_medium.png
  styles/LoginPageStyle.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가

#28 #24/feat/user profile edit
  pages/_app.tsx
  pages/userProfileEdit/index.tsx
  styles/LayoutStyle.tsx
  styles/UserProfileEditStyle.tsx
Labels: 리뷰 요청

#32 #22/feat/user profile
  components/TabPanel/TabPanel.tsx
  components/TabPanel/index.ts
  components/index.ts
  next.config.js
  pages/userProfile/index.tsx
  styles/UserProfileStyle.tsx
Labels: 리뷰 요청

#33 #27/feat/book detailpage
  components/BookCard/BookCard.tsx
  components/StudyCard/StudyCard.tsx
  components/StudyCard/style.tsx
  components/StudyContent/StudyContent.stories.tsx
  components/StudyContent/StudyContent.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  components/StudyDetailCard/index.ts
  components/StudyDetailCard/style.tsx
  features/StudyDetail/StudyDetail.stories.tsx
  features/StudyDetail/StudyDetail.tsx
  features/StudyDetail/index.ts
  features/StudyDetail/style.tsx
  next.config.js
  pages/book/[id].tsx
  styles/bookPageStyle.tsx
  types/bookType.ts
  types/studyType.ts
Labels: 리뷰 요청

#39 #37/hotfix 1st sprint merge
  apis/book.ts
  commons/dummy.ts
  components/StudyCard/StudyCard.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  pages/book/[id].tsx
  pages/userProfile/index.tsx
Labels: 리뷰 요청, 프론트, Type: 버그

#46 #38/feat/main page with api
  pages/index.tsx
  types/bookType.ts
Labels: 리뷰 요청, 프론트, API data, Type: 기능추가

#47 feat: 검색 페이지 추가. 책 검색 api, 책 클릭 이동 추가
  features/Topbar/Topbar.tsx
  pages/search/index.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가

#53 refactor: 모바일 버전에서 공통 레이아웃 margin 수정
  styles/LayoutStyle.tsx
Labels: Type: 리팩토링

#55 #43/feat/book detail api axios
  apis/book.ts
  apis/index.ts
  apis/study.ts
  features/StudyDetail/StudyDetail.tsx
  pages/book/[id].tsx
  types/studyType.ts
Labels: 리뷰 요청

#56 #51/feat/study card list
  features/StudyCardList/StudyCardList.tsx
  features/StudyCardList/index.ts
  features/StudyCardList/style.tsx
  features/index.ts
  pages/book/[id].tsx
Labels: 리뷰 요청

#60 feat: BookDetail 스터디개설하기 버튼 위치 변경
  components/BookDetailCard/BookDetailCard.tsx
  components/BookDetailCard/style.tsx
Labels: 리뷰 요청

#67 #54/feat/login context api
  apis/api.ts
  apis/index.ts
  apis/user.ts
  contexts/UserContextProvider.tsx
  features/Topbar/LoginButton/LoginButton.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/LogoutModal.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  features/Topbar/UserProfile/style.tsx
  hooks/useUserContext.ts
  pages/_app.tsx
  pages/login/index.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급

#68 #30/feat/study detail page
  features/StudyDetail/StudyDetail.tsx
  next.config.js
  pages/study/[id].tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가

#69 #63/feat/post
  components/BookCard/BookCard.tsx
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCard.tsx
  components/PostCard/index.ts
  components/PostCard/style.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가

#75 #74/refactor: 공통 API 사용
  pages/index.tsx
Labels: 프론트, Priority: 천천히, Type: 리팩토링

#78 #62/feat/post page UI
  pages/post/[id].tsx
  styles/PostStyle.tsx
Labels: 프론트, Type: 기능추가, Priority: 중간

#84 #64/fix/type unification - user, study, book
  apis/book.ts
  apis/user.ts
  commons/dummy.ts
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCard.tsx
  components/StudyCard/StudyCard.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  contexts/UserContextProvider.tsx
  features/StudyCardList/StudyCardList.tsx
  pages/_app.tsx
  pages/book/[id].tsx
  pages/index.tsx
  types/bookType.ts
  types/studyType.ts
  types/userType.ts
Labels: 백엔드, 프론트, API data, Priority: 긴급, Type: 리팩토링, Type: 버그

#72 #70/feat/snackbar
  contexts/UserContextProvider.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/LogoutModal.tsx
  hooks/useOurSnackbar/index.ts
  hooks/useOurSnackbar/style.ts
  hooks/useOurSnackbar/useOurSnackbar.tsx
  package.json
  pages/_app.tsx
  pages/login/index.tsx
  yarn.lock
Labels: 리뷰 요청, 프론트, Type: 기능추가

#81 #58/feat/user profile edit with api
  apis/image.ts
  apis/index.ts
  apis/user.ts
  pages/userProfileEdit/index.tsx
  styles/UserProfileEditStyle.tsx
Labels: 리뷰 요청

#80 #77/feat/post detail comments
  components/Comment/Comment.stories.tsx
  components/Comment/Comment.tsx
  components/Comment/index.ts
  components/Comment/style.tsx
  components/CommentInput/CommentInput.stories.tsx
  components/CommentInput/CommentInput.tsx
  components/CommentInput/index.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간

#82 #57/feat/user profile/id
  apis/index.ts
  apis/user.ts
  pages/userProfile/[id].tsx
  pages/userProfile/index.tsx
Labels: 리뷰 요청

#94 #90/refactor/topbar
  apis/user.ts
  contexts/UserContextProvider.tsx
  features/Topbar/LoginButton/LoginButton.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  features/Topbar/UserProfile/style.tsx
  features/Topbar/style.tsx
  pages/login/index.tsx
  types/userType.ts
Labels: 리뷰 요청, 프론트, Type: 리팩토링

#97 #88/feat/post create page
  pages/postCreate/index.tsx
  pages/userProfile/[id].tsx
  styles/PostCreatePageStyle.tsx
Labels: 리뷰 요청

#85 #66/feat/study recruitining share
  apis/study.ts
  components/StudyDetailCard/StudyDetailCard.tsx
  components/StudyDetailCard/style.tsx
  pages/book/[id].tsx
Labels: 리뷰 요청

#105 #71/refactor/search page
  apis/book.ts
  apis/index.ts
  apis/naver.ts
  features/SearchPageModal/SearchPageModal.tsx
  features/SearchPageModal/index.tsx
  features/SearchPageModal/style.tsx
  features/Topbar/Topbar.tsx
  pages/search/index.tsx
  styles/SearchPageStyle.ts
  types/bookType.ts
  types/errorTypes.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가

#98 #91/feat/ 스터디 개설 페이지 구현
  apis/study.ts
  features/StudyOpen/StudyOpen.tsx
  features/StudyOpen/style.tsx
  features/index.ts
  pages/api/hello.ts
  pages/studyOpen/[id].tsx
  styles/StudyOpenPageStyle.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간, Status: 진행중, Type: 리팩토링

#101 #92/feat/study detail pageapi
  components/Comment/Comment.stories.tsx
  components/Comment/Comment.tsx
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCard.tsx
  components/PostCard/style.tsx
  features/StudyCardList/StudyCardList.tsx
  pages/index.tsx
  pages/study/[id].tsx
  styles/StudyDetailPageStyle.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간

#99 #86/feat/infinite scroll
  apis/study.ts
  hooks/useInView.ts
  pages/book/[id].tsx
Labels: 리뷰 요청

#108 fix: dev 브랜치 에러 수정
  commons/dummy.ts
  commons/dummyPost.ts
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  features/StudyCardList/StudyCardList.tsx
  features/StudyDetail/StudyDetail.tsx
  pages/_app.tsx
  types/studyType.ts
Labels: 프론트, Priority: 긴급, Type: 버그

#115 refactor: 메인 페이지 북 카드 한 줄 ellipsis 처리
  components/BookCard/style.tsx
  pages/index.tsx
  styles/MainPageStyle.tsx
Labels: 리뷰 요청, 프론트, Priority: 긴급, Type: 리팩토링

#112 #111/refactor/study card list
  features/StudyCardList/StudyCardList.tsx
  features/StudyCardList/style.tsx
Labels: 리뷰 요청

#113 #89/feat/user profile with api
  apis/index.ts
  apis/study.ts
  apis/user.ts
  features/StudyOpen/style.tsx
  pages/userProfile/[id].tsx
  pages/userProfileEdit/index.tsx
  styles/UserProfileStyle.tsx
Labels: 리뷰 요청

#116 #103/feat/study detail tab
  .eslintrc.js
  components/NoAccess/NoAccess.stories.tsx
  components/NoAccess/NoAccess.tsx
  components/NoAccess/index.ts
  components/NoAccess/style.tsx
  features/ApplicantList/ApplicantList.stories.tsx
  features/ApplicantList/ApplicantList.tsx
  features/ApplicantList/index.ts
  features/ApplicantList/style.tsx
  pages/index.tsx
  pages/study/[id].tsx
  styles/StudyDetailPageStyle.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간

#118 #117/feat/Post Detail Add Input
  pages/post/[id].tsx
  pages/study/[id].tsx
  styles/PostStyle.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급, Priority: 중간

#120 #100/스터디개설페이지 마무리 - userConext를 사용하여 비로그인시 NoAccess
  features/StudyOpen/StudyOpen.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급, Status: 진행중

#121 #114/feat/Post 수정 생성 페이지와 기능 구현
  apis/index.ts
  apis/post.ts
  features/PostForm/PostForm.tsx
  features/PostForm/index.ts
  features/PostForm/style.tsx
  features/index.ts
  pages/postCreate/index.tsx
  pages/postUpdate/[id].tsx
Labels: 리뷰 요청

#127 #119/feat/study detail page api
  apis/applicant.ts
  apis/index.ts
  apis/post.ts
  commons/dummyPost.ts
  components/PostCard/PostCard.tsx
  components/PostCard/style.tsx
  features/ApplicantList/Applicant/Applicant.stories.tsx
  features/ApplicantList/Applicant/Applicant.tsx
  features/ApplicantList/Applicant/index.ts
  features/ApplicantList/Applicant/style.tsx
  features/ApplicantList/ApplicantList.tsx
  features/ApplicantList/style.tsx
  pages/study/[id].tsx
  styles/StudyDetailPageStyle.tsx
  types/applicantType.ts
  types/postType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급

#123 #109/feat/component skeleton
  components/BookCard/BookCard.stories.tsx
  components/BookCard/BookCardSkeleton.tsx
  components/BookCard/index.ts
  components/BookCard/style.tsx
  components/BookDetailCard/BookDetailCard.stories.tsx
  components/BookDetailCard/BookDetailCardSkeleton.tsx
  components/BookDetailCard/index.ts
  components/BookDetailCard/style.tsx
  components/Comment/Comment.stories.tsx
  components/Comment/CommentSkeleton.tsx
  components/Comment/index.ts
  components/Comment/style.tsx
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCardSkeleton.tsx
  components/PostCard/index.ts
  components/PostCard/style.tsx
  components/StudyCard/StudyCard.stories.tsx
  components/StudyCard/StudyCardSkeleton.tsx
  components/StudyCard/index.ts
  components/StudyCard/style.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCardSkeleton.tsx
  components/StudyDetailCard/index.ts
  components/StudyDetailCard/style.tsx
  components/index.ts
  pages/search/index.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가

#125 #124/fix/logout
  features/Topbar/UserProfile/LogoutModal.tsx
  pages/_app.tsx
Labels: 리뷰 요청, 프론트, Priority: 긴급, Type: 리팩토링, Type: 버그

#130 #104/study edit page 구현
  apis/index.ts
  apis/study.ts
  features/StudyOpen/StudyOpen.tsx
  features/StudyOpen/style.tsx
  next.config.js
  pages/studyEdit/[id].tsx
  types/studyType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간, Status: 진행중

#132 #131/refactor/home
  apis/book.ts
  apis/index.ts
  features/HomeUI/HomeUI.tsx
  features/HomeUI/index.ts
  features/HomeUI/style.tsx
  hooks/useWindowSize.ts
  package.json
  pages/index.tsx
  public/images/main_book_1.jpeg
  public/images/main_book_2.jpeg
  public/images/main_book_3.jpeg
  styles/MainPageStyle.tsx
  styles/globals.css
  types/bookType.ts
  yarn.lock
Labels: 리뷰 요청, 프론트, Type: 기능개선, Type: 기능추가

#135 feat: 북페이지에서 스터디 개설페이지로 라우팅 기능 추가
  components/BookDetailCard/BookDetailCard.stories.tsx
  components/BookDetailCard/BookDetailCard.tsx
  pages/book/[id].tsx
Labels: 리뷰 요청, 코칭 요청, 프론트, Type: 기능추가, Priority: 천천히, Status: 진행중, Type: 리팩토링

#133 #128/feat/post crud
  apis/applicant.ts
  apis/index.ts
  apis/post.ts
  features/DeleteModal/DeleteModal.tsx
  features/DeleteModal/index.tsx
  features/DeleteModal/style.tsx
  features/PostForm/PostForm.tsx
  pages/post/[id].tsx
  pages/postCreate/index.tsx
  pages/postUpdate/[id].tsx
  pages/study/[id].tsx
  styles/PostStyle.tsx
  types/applicantType.ts
  types/postType.ts
Labels: 리뷰 요청

#139 #126/feat/post detail page comment api
  apis/api.ts
  apis/applicant.ts
  apis/comments.ts
  apis/index.ts
  apis/post.ts
  components/Comment/Comment.tsx
  components/Comment/style.tsx
  components/CommentInput/CommentInput.tsx
  features/ApplicantList/Applicant/Applicant.tsx
  features/ApplicantList/ApplicantList.tsx
  pages/post/[id].tsx
  pages/study/[id].tsx
  types/applicantType.ts
  types/commentType.ts
  types/postType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급

#140 스터디 개설, 수정 페이지 스켈레톤
  features/StudyOpen/StudyOpen.tsx
  next.config.js
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 천천히, Status: 진행중

#122 #110/feat/study create routing and study share snack bar
  apis/index.ts
  apis/study.ts
  components/BookDetailCard/BookDetailCard.tsx
  components/StudyContent/StudyContent.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  features/LoginRequestModal/LoginRequestModal.tsx
  features/LoginRequestModal/index.ts
  features/LoginRequestModal/style.tsx
  features/StudyDetail/StudyDetail.tsx
  pages/book/[id].tsx
  types/studyType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간

#143 #142/fix/dev
  apis/api.ts
  apis/applicant.ts
  apis/book.ts
  apis/comments.ts
  apis/post.ts
  apis/study.ts
  apis/user.ts
  commons/dummy.ts
  commons/dummyPost.ts
  components/Comment/Comment.stories.tsx
  components/Comment/Comment.tsx
  components/CommentInput/CommentInput.stories.tsx
  components/CommentInput/CommentInput.tsx
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCardSkeleton.tsx
  components/StudyCard/StudyCard.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  contexts/testContext.ts
  features/ApplicantList/Applicant/Applicant.tsx
  features/ApplicantList/ApplicantList.stories.tsx
  features/ApplicantList/ApplicantList.tsx
  features/StudyCardList/StudyCardList.tsx
  features/StudyDetail/StudyDetail.tsx
  features/StudyOpen/StudyOpen.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  features/Topbar/UserProfile/style.tsx
  hooks/useTest.ts
  pages/_app.tsx
  pages/book/[id].tsx
  pages/layoutTest/index.tsx
  pages/post/[id].tsx
  pages/postUpdate/[id].tsx
  pages/study/[id].tsx
  pages/studyEdit/[id].tsx
  pages/studyOpen/[id].tsx
  pages/studyRecruiting/[id].tsx
  pages/userProfile/[id].tsx
  pages/userProfileEdit/index.tsx
  types/studyType.ts
  types/testType.ts
  types/userType.ts
Labels: 리뷰 요청, 프론트, Type: 버그

#148 feat: 책 상세 로딩 구현
  pages/book/[id].tsx
Labels: 리뷰 요청

#152 #147/fix/color logo
  apis/index.ts
  apis/user.ts
  features/HomeUI/HomeUI.tsx
  features/Topbar/LoginButton/LoginButton.tsx
  features/Topbar/LoginButton/style.tsx
  features/Topbar/Topbar.tsx
  features/Topbar/style.tsx
  public/images/kakao_login_medium.png
  public/images/kakao_login_medium_wide.png
  public/images/logo.png
Labels: 리뷰 요청, 프론트, Type: 리팩토링

#153 #149/feat/study detail null - 스터디 모집 로딩 구현
  features/StudyDetail/StudyDetail.tsx
  styles/globals.css
Labels: 리뷰 요청

#151 #145/feat/study open 마무리 - 상태 관련 핸들링, 뒤로가기 등
  features/StudyOpen/StudyOpen.tsx
  features/Topbar/UserProfile/UserProfile.tsx
  pages/userProfileEdit/index.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간, Status: 진행중

#158 #157/refactor/post validation
  components/Comment/Comment.tsx
  features/ApplicantList/style.tsx
  features/PostForm/PostForm.tsx
  pages/post/[id].tsx
  styles/PostStyle.tsx
Labels: 리뷰 요청

#162 #159/fix/BookTitle 잘리는 문제 해결
  components/BookCard/style.tsx
Labels: 리뷰 요청

#165 #163/fix/image upload size
  features/StudyOpen/StudyOpen.tsx
  features/Topbar/UserProfile/style.tsx
  pages/userProfileEdit/index.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간, Status: 진행중, Type: 리팩토링, Type: 버그

#150 feat: 스터디모집 상태 서버로 받은 값으로 렌더링
  components/StudyDetailCard/StudyDetailCard.tsx
  components/StudyDetailCard/StudyState/StudyState.tsx
  components/StudyDetailCard/helper.ts
Labels: 리뷰 요청

#167 feat: StudyCard hover 효과 추가
  components/StudyCard/style.tsx
  features/StudyCardList/StudyCardList.tsx
  features/StudyCardList/style.tsx
Labels: 리뷰 요청

#171 #170/book detail image error
  components/BookDetailCard/BookDetailCard.tsx
Labels: 리뷰 요청

#174 feat: 자기가 쓴 코멘트는 색깔 추가
  components/Comment/Comment.tsx
  components/Comment/style.tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 천천히, Status: 진행중

#175 #146/feat/postand comment infinite scroll
  apis/comments.ts
  apis/post.ts
  components/Comment/Comment.tsx
  pages/post/[id].tsx
  pages/study/[id].tsx
  styles/StudyDetailPageStyle.tsx
  types/commentType.ts
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 긴급

#169 #168/feat/study detail page
  components/PostCard/style.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  components/StudyDetailCard/style.tsx
  pages/study/[id].tsx
Labels: 리뷰 요청, 프론트, Type: 기능추가, Priority: 중간, Status: 진행중, Type: 리팩토링

#172 #154/fix/auto login
  apis/api.ts
  apis/applicant.ts
  apis/book.ts
  apis/comments.ts
  apis/image.ts
  apis/index.ts
  apis/post.ts
  apis/ssrApi/ssrApi.ts
  apis/study.ts
  apis/user.ts
  features/StudyDetail/StudyDetail.tsx
  features/StudyOpen/StudyOpen.tsx
  features/Topbar/UserProfile/LogoutModal.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/login/index.tsx
  pages/post/[id].tsx
  pages/search/index.tsx
  pages/study/[id].tsx
  pages/userProfile/[id].tsx
  pages/userProfileEdit/index.tsx
  types/errorTypes.ts
Labels: 프론트, Type: 기능개선, Priority: 긴급

#177 fix: dev 충돌 병합 에러 수정
  apis/api.ts
  apis/naver.ts
  apis/study.ts
  apis/user.ts
  components/Comment/Comment.tsx
  components/Comment/CommentSkeleton.tsx
  components/PostCard/PostCard.stories.tsx
  components/PostCard/PostCardSkeleton.tsx
  components/StudyDetailCard/StudyDetailCard.stories.tsx
  components/StudyDetailCard/StudyDetailCard.tsx
  features/StudyDetail/style.tsx
  pages/_app.tsx
  pages/login/index.tsx
  pages/post/[id].tsx
  types/applicantType.ts
  types/studyType.ts
Labels: 리뷰 요청, 프론트, Priority: 긴급, Type: 버그

#182 #178/fix/login
  apis/api.ts
  features/Topbar/LoginButton/LoginButton.tsx
  features/Topbar/Topbar.tsx
  pages/_app.tsx
Labels: 리뷰 요청, 프론트, Type: 기능개선, Priority: 긴급

#186 #185/fix/short token login
  features/Topbar/LoginButton/LoginButton.tsx
  pages/index.tsx
Labels: 프론트, Type: 기능개선, Priority: 긴급

#188 docs: readme 업데이트
  README.md
Labels: 프론트, Priority: 긴급

#191 fix: 404 image layout 삭제
  pages/404.tsx
Labels: 프론트, Priority: 긴급, Type: 버그

#193 fix: next 기본 dark mode 스타일 삭제
  pages/index.tsx
  styles/globals.css
Labels: 리뷰 요청, 프론트, Priority: 긴급, Type: 버그

#195 fix: 누락된 dots 삭제
  pages/index.tsx
Labels: 리뷰 요청, 프론트, Priority: 긴급, Type: 버그
